site_name: Documentación que mola para clientes
site_description: Utilizando MkDocs.
site_author: Daniel Primo

use_directory_urls: false

repo_url: https://github.com/delineas/mkdocs-demo/

nav:
  - Home: index.md
  - "¿Qué es esta web?": about.md
  - Sección muy importante:
      - Primera subsección: section/first.md
      - Otro nombre muy original: section/second.md

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - def_list

theme:
  language: "es"
  name: "material"
  palette:
    primary: "purple"
    accent: "indigo"
  logo:
    icon: "cloud"
